// <auto-generated />
namespace Book_A_Room.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createItemsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createItemsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202105311832284_createItemsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
