// <auto-generated />
namespace Book_A_Room.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202106021239533_editItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
